CREATE DATABASE IF NOT EXISTS GEVEX;
USE GEVEX;

CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120),
  email VARCHAR(190) UNIQUE,
  bio VARCHAR(255),
  password VARCHAR(255)
);
